# Generated by Django 6.0.7 on 2026-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='history',
            field=models.TextField(blank=True, default='', verbose_name='История'),
        ),
    ]
